"""Add employer profile fields to User model

Revision ID: 60a6e3d8536a
Revises: 1b551c0b2201
Create Date: 2024-09-25 21:42:05.667186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a6e3d8536a'
down_revision = '1b551c0b2201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('company_description')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
