"""Add profile picture and description to User model

Revision ID: f22aa1f9d00e
Revises: 36eaef93eef3
Create Date: 2024-09-25 22:25:34.313083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22aa1f9d00e'
down_revision = '36eaef93eef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_description')

    # ### end Alembic commands ###
